### PR TITLE
fix for unit test keyspace

### PR DESCRIPTION
**Pull request by lsmithso**

### CODE REVIEW

**Comment by r4fek** [comment]
Wow, that looks really great! Thanks for contributing. I'll review this and merge tomorrow, because today I'm really swamped.

**Comment by r4fek** [comment]
@lsmithso Your changes were merged to master (with some minor modifications). Could you try if it works for you?

**Comment by lsmithso** [comment]
Hi: I'll check this out and get back to you as soon as I can -
probably in a couple of days.

Rafał Furmański writes:
 > @lsmithso Your changes were merged to master (with some minor modifications). Could you try if it works for you?
 > 
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/r4fek/django-cassandra-engine/pull/19#issuecomment-71371335

-- 
Les Smithson

**Comment by lsmithso** [comment]
Hi: Tested it and it works great.

Thanks.

Rafał Furmański writes:
 > @lsmithso Your changes were merged to master (with some minor modifications). Could you try if it works for you?
 > 
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/r4fek/django-cassandra-engine/pull/19#issuecomment-71371335

-- 
Les Smithson

**Comment by r4fek** [comment]
Good to know! Once again thanks for your contribution :+1:

**Pull request closed without merging**
